Displaying Pokemon Data from API
JuanDiegoGuerra/Module_2-Capstone pull request #24
Opened 2023-05-23 21:36 UTC by JuanDiegoGuerra

### Rendering API Data

- Use of APIs for:
   - Display Pokemon data
   - Display Pokemons' Likes

2023-05-23 22:13 UTC, lincoln1883 reviewed
Hey, @JuanDiegoGuerra good job so far on implementing the Api connections.

2023-05-23 22:17 UTC, lincoln1883 commented on src/modules/api_data.js
A recommendation from my side would be to use one file for the API calls and export them individually.

2023-05-23 22:19 UTC, lincoln1883 requested changes
Please make the necessary changes. 👍🏾

2023-05-24 01:04 UTC, JuanDiegoGuerra commented
###  Required changes made 🛠
**All linters are enable!**
- Fixed _"use one file for the API calls and export them individually"_ ✅
  - Now the app is adding 'likes' correctly!

![todolist1](https://user-images.githubusercontent.com/45726631/231703283-083f07c2-f037-4fa4-a834-be7d3bd26e06.gif)

2023-05-24 01:22 UTC, lincoln1883 approved these changes
Hello Juan good job on implementing the requested changes, you are free to merge your changes.

2023-05-24 01:32 UTC, merged