Pokedex - Module 2 - Group Capstone Project
JuanDiegoGuerra/Module_2-Capstone pull request #35
Opened 2023-05-25 22:05 UTC by JuanDiegoGuerra

### JavaScript capstone project - Your API-based webapp ( Module 2 )
 - Followed the project requirements and completed the 3 days Milestones of **"Your API-based webapp"** we completed the main requirements:
   - A home page showing a list of items that you can "like." ✅
   - A popup window with more data about an item that you can use to comment on it. ✅
   - Professional Documentation in a Readme file. ✅
- As part of the requirements, we recorded a video explaining how the page works. 
   - You can watch it here: [Loom Video - Pokedex - Module 2 - Group Capstone](https://www.loom.com/share/1446ee58f4574b658372ef24167a1272) ✅

**Preview : 🕵🏼‍♂️**

![final_preview_pokedex](https://github.com/JuanDiegoGuerra/Module_2-Capstone/assets/45726631/50bc3a41-45f7-4fb6-adb3-389d1cf8b2ca)

2023-05-25 22:48 UTC, Lucas-Masaba requested changes
# Hello @JuanDiegoGuerra  and @lincoln1883  👋 , 

Good job so far! 👍 
There are some issues that you still need to work on to go to the next project but you are almost there!

![almost-there](https://media.giphy.com/media/ReyD4OdRiHeLDCRaEP/giphy.gif)

## Highlights 🍾 
- Linter checks and unit tests are passing :heavy_check_mark: 
- Good use of ES6 :surfer: 
- Well-written commit messages :+1: 
- Successfully used an API :snowboarder: 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions 💭 
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @Lucas-Masaba in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-25 22:48 UTC, Lucas-Masaba commented on src/modules/pokemons.js
> +              <button type="button" id="${id + 1}" class="comment">Comments</button>
- [ ] I am able to see the comments only on the mobile view. I cannot see them on the desktop view. Even on the mobile view, I find it hard to read the comments. Please ensure that the comments written can be seen clearly as seen in the wireframe :+1: 

### View of comments on the mobile screen
![image](https://github.com/JuanDiegoGuerra/Module_2-Capstone/assets/45460192/fe550cc5-893a-466c-802a-f54f3b35ce6d)

### View of comments on the desktop view
![image](https://github.com/JuanDiegoGuerra/Module_2-Capstone/assets/45460192/ad2a8e24-b6ae-4e11-8cf0-4a334973a9ef)

2023-05-26 00:53 UTC, JuanDiegoGuerra commented
###  Required changes made 🛠
**All linters are enable!**

- Added Media Query ✅
- Fixed _"I am able to see the comments only on the mobile view. I cannot see them on the desktop view. Even on the mobile view, I find it hard to read the comments. Please ensure that the comments written can be seen clearly as seen in the wireframe 👍"_ ✅
  - Now the app is working correctly!

![todolist1](https://user-images.githubusercontent.com/45726631/231703283-083f07c2-f037-4fa4-a834-be7d3bd26e06.gif)

**Preview 🕵🏼‍♂️:**

![requested_changes_preview](https://github.com/JuanDiegoGuerra/Module_2-Capstone/assets/45726631/72eeed69-7dc3-4dbc-82b4-c6c16957f5d5)

2023-05-26 01:11 UTC, jerryowusu approved these changes
Hi @JuanDiegoGuerra and @lincoln1883 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 


![weldone](https://github.com/JuanDiegoGuerra/Module_2-Capstone/assets/65233860/925b7eea-f1b4-46c5-92d0-f0dcc0f77b7e)


## Highlights
Nice design :+1: 
API working fine :+1: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-26 14:44 UTC, merged